### ISSUE TITLE
FreeBSD support?

### ISSUE THREAD

**Issue by jan666** [steilerDev/icloud-photos-sync#216]
Hello,

I just wanted to try this out but it looks like FreeBSD is not supported:

```
npm ERR! code EBADPLATFORM
npm ERR! notsup Unsupported platform for icloud-photos-sync@1.1.0: wanted {"os":"linux,darwin,!win32"} (current: {"os":"freebsd","arch":"x64"})
npm ERR! notsup Valid OS:    linux,darwin,!win32
npm ERR! notsup Valid Arch:  undefined
npm ERR! notsup Actual OS:   freebsd
npm ERR! notsup Actual Arch: x64
```

is this on purpose or could freebsd be added to the "wanted" list?

**Comment by steilerDev** [comment]
I'm taking a conservative approach to the OS support since large parts of the codebase make assumptions about the file system (how symlinks are handled, a lot of fs interactions). 

Unfortunately I currently don't have a way to validate FreeBSD compatibility. Given fs interactions are probably simliar from node's perspective, you should be fine running it - however I don't know how I could ensure continued functionality and therefore I can't add 'official' support (and it seems there is no way to add unofficial support to the `package.json`)

Two options here: Use Docker (the image is Alpine based and this works fine) - pull the repo change `package.json` and build and run it yourself (or download the asset attached to the latest release which already contains the built application).
