### ISSUE TITLE
Feature Request: Separate Config & Photo Volumes

### ISSUE THREAD

**Issue by undaunt** [steilerDev/icloud-photos-sync#299]
Hello,

I was wondering if the configuration portion of the tool (trust token, log file, not sure about anything else) be stored by default in a different location than `/opt/icloud-photos-library` essentially splitting up config and data.

The benefit here would be logging to an SSD or just another configuration location while I keep the media contents on a larger NAS array, not having to then exclude the log file specifically from snapraid, etc.

I'm testing working around the issue now by bind mounting the log file and the trust token to a different location, and I imagine I could create the same situation by explicitly declaring the trust token flag to live elsewhere, but I didn't see an option to do that with logs, only log-to-cli.

Thanks!

**Comment by steilerDev** [comment]
This shouldn't be too hard - let me see when I can squeeze it in.

**Comment by steilerDev** [comment]
I've started working on this feature request, and as always: the devil is in the details :D 

While it's not difficult to implement, there are a couple of UX as well as technical considerations, that -imho- outweigh the benefits, which is why I won't be implementing this:

- By default those files are hidden (by being prefixed with `.`) - therefore a separate config directory would look empty to the user
- The tool could unhide the files if stored in a different directory, however a lot of pieces of documentation would now need to take two directories/file names into consideration
- Besides the log file, none of those files is heavily written to:
  - Network capture har file is only written to once (if network capture is enabled)
  - Resource file (which succeeded trust token file) is only written to if the trust token changes
  - Metrics file is only receiving minimal amount of data during each sync run (and only if metrics export is enabled)

As you've mentioned, if this is really important to you, you can map out the `.icloud-photos-sync.log` file and disable the other features. Alternatively you could skip the log file and use `--log-to-cli` for printing the log to stdout instead of writing it to the log file.

I hope this makes sense!
