### ISSUE TITLE
Feature Request: Remove password from environment

### ISSUE THREAD

**Issue by lonevvolf** [steilerDev/icloud-photos-sync#341]
### Describe the ultimate goal you want to achieve

Currently, having to store the password in the environment is a bit unsecure.  In order to make this work, I have to setup the variables for the Docker container outside of the container itself, so they are clearly visible on that level (in my case, in Synology Container Manager).  It would be great to have a flow where when no password is submitted, it can be filled in at the command line at first startup and cached in a secure way in the container storage.

### How do you think the feature should be implemented

On first setup, it should be possible to send the password via command line to the container, and it would be encrypted and cached.  icloudpd works in a similar way.

### Checklist

- [X] This is a [feature request](https://github.com/steilerDev/icloud-photos-sync/blob/main/CONTRIBUTING.md#feature), not an [issue](https://github.com/steilerDev/icloud-photos-sync/blob/main/CONTRIBUTING.md#issue) or [a question](https://github.com/steilerDev/icloud-photos-sync/blob/main/CONTRIBUTING.md#question)
- [X] Checked out [existing feature requests](https://github.com/steilerDev/icloud-photos-sync/issues?q=is%3Aopen+is%3Aissue+label%3Aclass%28feature%29+label%3Astatus%28open%29%2Cstatus%28wontfix%29%2Cstatus%28backlog%29%2C%22status%28help+needed%29%22%2C%22status%28in+progress%29%22%2Cstatus%28investigating%29%2Cstatus%28previewed%29+)

**Comment by steilerDev** [comment]
This makes sense - however I don't mind having those credentials visible on the container level (because the account is MFA secured - and the MFA trust token is location bound - meaning that even if password and token are stolen, the attacker needs to have an IP that is close to mine)

Nevertheless I understand the security implications and are already implementing the following: The CLI can be started with an empty password - if this is the case, it will prompt the user to enter it through the CLI. This password will be held in memory until the application exits.

**Comment by lonevvolf** [comment]
How does this work in combination with daemon mode?

**Comment by steilerDev** [comment]
The password is requested when starting the daemon mode and kept in memory for all runs until the process is stopped.

**Comment by steilerDev** [comment]
Have a look at the documentation: https://github.com/steilerDev/icloud-photos-sync/blob/3ac703f66ded2a2500ac5caca65290d5eaf5dc4b/docs/src/get-started.md?plain=1#L59

**Comment by steilerDev** [comment]
[1.3.0-beta.1]https://github.com/steilerDev/icloud-photos-sync/releases/tag/v1.3.0-beta.1) improves on the machanism.
